### PR TITLE
Corrected typo / misleading function name

### PR DESCRIPTION
**Pull request by TillF**
Corrected typo "pft.rawls" to "ptf.rawls". Updated docu.
Sorry for the confusion I introduced two years ago.

### CODE REVIEW

**Comment by jeroen** [comment]
This is a read only mirror. You need to send patches to https://r-forge.r-project.org/projects/soilwater

**Comment by TillF** [comment]
Only project developers have access to the r-forge repo.
So, you could sign me up or checkout my github-repo and commit the changes yourselfs.

**Comment by jeroen** [comment]
I am not affiliated with them, just pointing this out to you.

**Comment by TillF** [comment]
OK, my wrong. I had assumed they would be notified, too. I will contact them, thanks.

**Pull request closed without merging**
